name: dynacontrast
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - dask
  - matplotlib
  - numpy
  - natsort
  - opencv
  - pandas
  - PyYAML
  - scikit-image
  - scikit-learn
  - scipy
  - pytorch==1.2.0
  - tqdm
  - torchvision==0.4.0
  - zarr
