preprocess:
  raw_dirs: [
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0001-1',  
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0002-1',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0003-1',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0004-1',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0006-1',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0007-1',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0008-1',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0009-1',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0015-1',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0016-1',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0017-1',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0018-1',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0020-1',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0021-1',          
            ]

  supp_dirs: [
           '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0001-1_patch',
           '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0002-1_patch',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0003-1_patch',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0004-1_patch',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0006-1_patch',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0007-1_patch',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0008-1_patch',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0009-1_patch',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0015-1_patch',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0016-1_patch',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0017-1_patch',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0018-1_patch',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0020-1_patch',
#          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0021-1_patch',          
             ]
  channels: [0,1]
  fov: null
  num_workers: 20
  crop_size: 200
  patch_size: 100
  save_fig: False
  skip_boundary: True
  
#  min_length: 2
#  track_dim: 'slice'
  

data_pooling:
  raw_dirs: [
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0001-1',  
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0002-1',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0003-1',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0004-1',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0006-1',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0007-1',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0008-1',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0009-1',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0015-1',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0016-1',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0017-1',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0018-1',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0020-1',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0021-1',          
            ]

  supp_dirs: [
           '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0001-1_patch',
           '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0002-1_patch',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0003-1_patch',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0004-1_patch',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0006-1_patch',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0007-1_patch',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0008-1_patch',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0009-1_patch',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0015-1_patch',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0016-1_patch',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0017-1_patch',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0018-1_patch',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0020-1_patch',
          '/gpfs/CompMicro/projects/dynacontrast/tic/TICM0021-1_patch',          
             ]
  dst_dir:  '/gpfs/CompMicro/projects/dynacontrast/tic/TIC_pool'
  splits: ['train', 'val']
  split_cols: ['gene']
  split_ratio: 0.15


inference:
  raw_dirs: [  
          '/gpfs/CompMicro/projects/dynacontrast/tic/TIC_pool' 
            ]

  supp_dirs: [
          '/gpfs/CompMicro/projects/dynacontrast/tic/TIC_pool'
             ]

  weights: [
#            '/gpfs/CompMicro/projects/dynacontrast/opencell/2021-7-15_good-fovs/models/rot_crop_jit_ntxent_0.5',
#            '/gpfs/CompMicro/projects/dynacontrast/opencell/2021-7-15_good-fovs/models/rot_crop_jit_ntxent_0.1',
#            '/gpfs/CompMicro/projects/dynacontrast/opencell/2021-7-15_good-fovs/models/rot_crop_jit_ntxent_2',
#            '/gpfs/CompMicro/projects/dynacontrast/opencell/2021-7-15_good-fovs/models/rot_crop_jit_triplet',
#            '/gpfs/CompMicro/projects/dynacontrast/opencell/2021-7-15_good-fovs/models/rot_crop_jit_ntxent_2_label_protein',
            '/gpfs/CompMicro/projects/dynacontrast/tic/TIC_pool/models/tic_ntxent_2_label_gene+expid+condi',
            '/gpfs/CompMicro/projects/dynacontrast/tic/TIC_pool/models/tic_ntxent_2'
            ]  # pytorch weight files

  network: 'ResNet50'
  network_width: 1
  projection: False
  gpu_ids: 2  # list of GPUs to run inference on.
  fov: False
  channels: [0,1]
  normalization: patch
  splits: ['all']
  batch_size: 1024
  num_workers: 24

dim_reduction:
  input_dirs:
  output_dirs:
  file_name_prefixes:
  weights_dirs:
  fit_model:
  conditions:


training:
  raw_dir: '/gpfs/CompMicro/projects/dynacontrast/tic/TIC_pool' 
  weights_dir: '/gpfs/CompMicro/projects/dynacontrast/tic/TIC_pool/models'
  # model hyperparameters
  network: 'ResNet50'
  network_width: 1
  num_inputs: 2
  margin: 1

  # data
  channels: [0,1]
  channel_mean: null
  channel_std: null

  # training parameters

  n_epochs: 5000
  learn_rate: 0.0001
  batch_size: 1280
  shuffle_data: False
  transform: True
  patience: 100
  n_pos_samples: 2
  num_workers: 24
  start_model_path: null
  use_mask: False
#  start_model_path: '/CompMicro/projects/virtualstaining/kidneyslice/2019_02_15_kidney_slice/dnm_train/CM+kidney_ResNet101_mrg1_npos4_bh512_alltriloss/model.pt'
  retrain: True
  start_epoch: 0
#  earlystop_metric: positive_triplet
  earlystop_metric: total_loss # 'total_loss' or 'positive_triplet' for triplet loss 
  model_name: 'tic_ntxent_2_label_gene+expid+condi'
  normalization: patch
#  loss: triplet # triplet or ntxent
  loss: ntxent # triplet or ntxent 
  temperature: 2
  label_cols: ['gene', 'experiment ID', 'condition']
  augmentations:
    rotate_range: 180
    intensity_jitter: [0.5, 0.5]
  gpu_id: 2


  

