patch:
  raw_dirs: [
             '/CompMicro/projects/cardiomyocytes/200721_CM_Mock_SPS_Fluor/20200721_CM_Mock_SPS/dnm_input_tstack',
              '/CompMicro/projects/cardiomyocytes/20200722CM_LowMOI_SPS_Fluor/20200722 CM_LowMOI_SPS/dnm_input_tstack',
              '/CompMicro/projects/virtualstaining/kidneyslice/2019_02_15_kidney_slice/dnm_input',
#              '/CompMicro/projects/A549/20210209_Falcon_3D_uPTI_A549_RSV_registered/Mock_24h_right/dnm_input',
#              '/CompMicro/projects/A549/20210209_Falcon_3D_uPTI_A549_RSV_registered/Mock_48h_right/dnm_input',
#              '/CompMicro/projects/A549/20210209_Falcon_3D_uPTI_A549_RSV_registered/RSV_24h_right/dnm_input',
#              '/CompMicro/projects/A549/20210209_Falcon_3D_uPTI_A549_RSV_registered/RSV_48h_right/dnm_input',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/MOCK_IFNA_48/dnm_input',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNA_24/dnm_input',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNA_48/dnm_input',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNL_24/dnm_input'
            ]

  supp_dirs: [
             '/CompMicro/projects/cardiomyocytes/200721_CM_Mock_SPS_Fluor/20200721_CM_Mock_SPS/dnm_supp_tstack',
             '/CompMicro/projects/cardiomyocytes/20200722CM_LowMOI_SPS_Fluor/20200722 CM_LowMOI_SPS/dnm_supp_tstack',
             '/CompMicro/projects/virtualstaining/kidneyslice/2019_02_15_kidney_slice/dnm_supp',
#             '/CompMicro/projects/A549/20210209_Falcon_3D_uPTI_A549_RSV_registered/Mock_24h_right/dnm_supp',
#             '/CompMicro/projects/A549/20210209_Falcon_3D_uPTI_A549_RSV_registered/Mock_48h_right/dnm_supp',
#             '/CompMicro/projects/A549/20210209_Falcon_3D_uPTI_A549_RSV_registered/RSV_24h_right/dnm_supp',
#             '/CompMicro/projects/A549/20210209_Falcon_3D_uPTI_A549_RSV_registered/RSV_48h_right/dnm_supp',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/MOCK_IFNA_48/dnm_supp',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNA_24/dnm_supp',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNA_48/dnm_supp',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNL_24/dnm_supp'
             ]

  channels: [0,1]
  fov: null
  num_cpus: 50
  window_size: 128
  save_fig: False
  reload: False
  skip_boundary: True
  min_length: 2
  track_dim: 'slice'


segmentation:
  raw_dirs: [  
#              '/CompMicro/projects/cardiomyocytes/200721_CM_Mock_SPS_Fluor/20200721_CM_Mock_SPS/dnm_input_tstack',
#              '/CompMicro/projects/cardiomyocytes/20200722CM_LowMOI_SPS_Fluor/20200722 CM_LowMOI_SPS/dnm_input_tstack',
#              '/CompMicro/projects/virtualstaining/kidneyslice/2019_02_15_kidney_slice/dnm_input',
#              '/CompMicro/projects/A549/20210209_Falcon_3D_uPTI_A549_RSV_registered/Mock_24h_right/dnm_input',
#              '/CompMicro/projects/A549/20210209_Falcon_3D_uPTI_A549_RSV_registered/Mock_48h_right/dnm_input',
#              '/CompMicro/projects/A549/20210209_Falcon_3D_uPTI_A549_RSV_registered/RSV_24h_right/dnm_input',
#              '/CompMicro/projects/A549/20210209_Falcon_3D_uPTI_A549_RSV_registered/RSV_48h_right/dnm_input',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/MOCK_IFNA_48/dnm_input',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNA_24/dnm_input',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNA_48/dnm_input',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNL_24/dnm_input'
            ]

  supp_dirs: [
#             '/CompMicro/projects/cardiomyocytes/200721_CM_Mock_SPS_Fluor/20200721_CM_Mock_SPS/dnm_supp_tstack',
#             '/CompMicro/projects/cardiomyocytes/20200722CM_LowMOI_SPS_Fluor/20200722 CM_LowMOI_SPS/dnm_supp_tstack',
#             '/CompMicro/projects/virtualstaining/kidneyslice/2019_02_15_kidney_slice/dnm_supp',
#             '/CompMicro/projects/A549/20210209_Falcon_3D_uPTI_A549_RSV_registered/Mock_24h_right/dnm_supp',
#             '/CompMicro/projects/A549/20210209_Falcon_3D_uPTI_A549_RSV_registered/Mock_48h_right/dnm_supp',
#             '/CompMicro/projects/A549/20210209_Falcon_3D_uPTI_A549_RSV_registered/RSV_24h_right/dnm_supp',
#             '/CompMicro/projects/A549/20210209_Falcon_3D_uPTI_A549_RSV_registered/RSV_48h_right/dnm_supp',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/MOCK_IFNA_48/dnm_supp',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNA_24/dnm_supp',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNA_48/dnm_supp',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNL_24/dnm_supp'
             ]
  val_dirs: [null, null, null, null]

  weights: '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNL_24/dnm_train/CM+kidney+A549_QLIPP_ResNet50_notrj_patchnorm_rot/model.pt'
  # pytorch weight files

  model: 'ResNet50'

  save_output: True
  # write .jpg results from run_vae.process

  gpu_ids: [0]
  # list of GPUs to run inference on.
  num_workers: 20
  fov: False
  channels: [0,1]
  channel_mean:
  channel_std:
  num_classes: 3
  window_size: 256
  batch_size: 8
  num_pred_rnd: 5
  seg_val_cat: 'mg'

data_pooling:
  raw_dirs: [  
              '/CompMicro/projects/cardiomyocytes/200721_CM_Mock_SPS_Fluor/20200721_CM_Mock_SPS/dnm_input_tstack',
              '/CompMicro/projects/cardiomyocytes/20200722CM_LowMOI_SPS_Fluor/20200722 CM_LowMOI_SPS/dnm_input_tstack',
              '/CompMicro/projects/virtualstaining/kidneyslice/2019_02_15_kidney_slice/dnm_input',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/MOCK_IFNA_48/dnm_input',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNA_24/dnm_input',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNA_48/dnm_input',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNL_24/dnm_input'
            ]
  supp_dirs: [
             '/CompMicro/projects/cardiomyocytes/200721_CM_Mock_SPS_Fluor/20200721_CM_Mock_SPS/dnm_supp_tstack',
             '/CompMicro/projects/cardiomyocytes/20200722CM_LowMOI_SPS_Fluor/20200722 CM_LowMOI_SPS/dnm_supp_tstack',
             '/CompMicro/projects/virtualstaining/kidneyslice/2019_02_15_kidney_slice/dnm_supp',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/MOCK_IFNA_48/dnm_supp',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNA_24/dnm_supp',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNA_48/dnm_supp',
             '/CompMicro/projects/A549/2021_02_25_40X_04NA_A549_tif_registered/RSV_IFNL_24/dnm_supp'
             ]          
  dst_dir:  '/CompMicro/projects/dynacontrast/4_cell_types'
  val_split_ratio: 0.15  

inference:
  raw_dirs: ['/gpfs/CompMicro/projects/dynacontrast/4_cell_types']

  supp_dirs: ['/gpfs/CompMicro/projects/dynacontrast/4_cell_types']

  weights: ['/gpfs/CompMicro/projects/dynacontrast/4_cell_types/models/triplet_test'] # pytorch weight files

  network: 'ResNet50'
  network_width: 1
  projection: True

  gpu_ids: [0]
  # list of GPUs to run inference on.
  fov: False
  channels: [0,1]
  normalization: patch
  batch_size: 384
  num_workers: 16

training:
  raw_dir: '/CompMicro/projects/dynacontrast/4_cell_types'
  weights_dir: '~/dnm_train'
  # model hyperparameters
  network: 'ResNet50'
  network_width: 1
  num_inputs: 2
  margin: 1

  # data
  channels: [0,1]
  channel_mean: null
  channel_std: null

  # training parameters

  n_epochs: 5000
  learn_rate: 0.0001
  batch_size: 768
  val_split_ratio: 0.15
  shuffle_data: False
  transform: True
  patience: 100
  n_pos_samples: 2
  num_workers: 24
  start_model_path: null
  use_mask: False
#  start_model_path: '/CompMicro/projects/virtualstaining/kidneyslice/2019_02_15_kidney_slice/dnm_train/CM+kidney_ResNet101_mrg1_npos4_bh512_alltriloss/model.pt'
  retrain: True
  start_epoch: 0
  earlystop_metric: 'total_loss'
  model_name: 'test_model'
  normalization: patch
  loss: ntxent
  temperature: 0.5
  augmentations:
    rotate_range: 180
    intensity_jitter: [0.5, 0.5]
  gpu_id: 0


  

